version: '2'
services:
  mysql2:
        image: mysql:8.0
        container_name: mysql2
        command: --default-authentication-plugin=mysql_native_password
        volumes:
          - ./MySQL:/var/lib/mysql
        restart: unless-stopped
        environment:
          - MYSQL_ROOT_PASSWORD=clave123
          - MYSQL_DATABASE=aplicacionz
        ports:
          - "33061:3306"
  php2:
    container_name: php2
    build:
      context: ./
    volumes:
      - ./app:/var/www/html
    ports:
      - 82:80
    depends_on:
      - mysql2